#pragma once

#include "../tone_player.h"
#include "../musical_frequencies.h"

// https://www.musicbody.net/sns/index.php?s=/news/index/detail/id/520.html
#define BPM (150)
#define BPM_TO_USPB(bpm) (60000000 / (bpm))
#define TONE_WHOLE_NOTE (BPM_TO_USPB(BPM) * 4)
#define TONE_HALF_NOTE (BPM_TO_USPB(BPM) * 2)
#define TONE_QUARTER_NOTE BPM_TO_USPB(BPM)
#define TONE_EIGHTH_NOTE (BPM_TO_USPB(BPM) / 2)
#define TONE_SIXTEENTH_NOTE (BPM_TO_USPB(BPM) / 4)
#define TONE_THIRTY_SECOND_NOTE (BPM_TO_USPB(BPM) / 8)
#define TONE_BREAK_NOTE (10e3)

static tone_t tones_main[] = {
    // 0 (pre)
    {NOTE_MAXIMUM, TONE_WHOLE_NOTE},
    // 1
    {NOTE_D4, TONE_QUARTER_NOTE - TONE_BREAK_NOTE},
    {NOTE_MAXIMUM, TONE_BREAK_NOTE},
    {NOTE_D4, TONE_QUARTER_NOTE},
    // 2
    {NOTE_A4, TONE_QUARTER_NOTE - TONE_BREAK_NOTE},
    {NOTE_MAXIMUM, TONE_BREAK_NOTE},
    {NOTE_A4, TONE_QUARTER_NOTE},
    // 3
    {NOTE_B4, TONE_QUARTER_NOTE - TONE_BREAK_NOTE},
    {NOTE_MAXIMUM, TONE_BREAK_NOTE},
    {NOTE_B4, TONE_QUARTER_NOTE},
    // 4
    {NOTE_A4, TONE_HALF_NOTE},
    // 5
    {NOTE_G4, TONE_QUARTER_NOTE - TONE_BREAK_NOTE},
    {NOTE_MAXIMUM, TONE_BREAK_NOTE},
    {NOTE_G4, TONE_QUARTER_NOTE},
    // 6
    {NOTE_F4, TONE_QUARTER_NOTE - TONE_BREAK_NOTE},
    {NOTE_MAXIMUM, TONE_BREAK_NOTE},
    {NOTE_F4, TONE_QUARTER_NOTE},
    // 7
    {NOTE_E4, TONE_QUARTER_NOTE - TONE_BREAK_NOTE},
    {NOTE_MAXIMUM, TONE_BREAK_NOTE},
    {NOTE_E4, TONE_QUARTER_NOTE},
    // 8
    {NOTE_D4, TONE_HALF_NOTE},
    // 9
    {NOTE_A4, TONE_QUARTER_NOTE - TONE_BREAK_NOTE},
    {NOTE_MAXIMUM, TONE_BREAK_NOTE},
    {NOTE_A4, TONE_QUARTER_NOTE},
    // 10
    {NOTE_G4, TONE_QUARTER_NOTE - TONE_BREAK_NOTE},
    {NOTE_MAXIMUM, TONE_BREAK_NOTE},
    {NOTE_G4, TONE_QUARTER_NOTE},
    // 11
    {NOTE_F4, TONE_QUARTER_NOTE - TONE_BREAK_NOTE},
    {NOTE_MAXIMUM, TONE_BREAK_NOTE},
    {NOTE_F4, TONE_QUARTER_NOTE},
    // 12
    {NOTE_E4, TONE_HALF_NOTE},
    // 13
    {NOTE_A4, TONE_QUARTER_NOTE - TONE_BREAK_NOTE},
    {NOTE_MAXIMUM, TONE_BREAK_NOTE},
    {NOTE_A4, TONE_QUARTER_NOTE},
    // 14
    {NOTE_G4, TONE_QUARTER_NOTE - TONE_BREAK_NOTE},
    {NOTE_MAXIMUM, TONE_BREAK_NOTE},
    {NOTE_G4, TONE_QUARTER_NOTE},
    // 15
    {NOTE_F4, TONE_QUARTER_NOTE - TONE_BREAK_NOTE},
    {NOTE_MAXIMUM, TONE_BREAK_NOTE},
    {NOTE_F4, TONE_QUARTER_NOTE},
    // 16
    {NOTE_E4, TONE_HALF_NOTE},
    // 17
    {NOTE_D4, TONE_QUARTER_NOTE - TONE_BREAK_NOTE},
    {NOTE_MAXIMUM, TONE_BREAK_NOTE},
    {NOTE_D4, TONE_QUARTER_NOTE},
    // 18
    {NOTE_A4, TONE_QUARTER_NOTE - TONE_BREAK_NOTE},
    {NOTE_MAXIMUM, TONE_BREAK_NOTE},
    {NOTE_A4, TONE_QUARTER_NOTE},
    // 19
    {NOTE_B4, TONE_QUARTER_NOTE - TONE_BREAK_NOTE},
    {NOTE_MAXIMUM, TONE_BREAK_NOTE},
    {NOTE_B4, TONE_QUARTER_NOTE},
    // 20
    {NOTE_A4, TONE_HALF_NOTE},
    // 21
    {NOTE_G4, TONE_QUARTER_NOTE - TONE_BREAK_NOTE},
    {NOTE_MAXIMUM, TONE_BREAK_NOTE},
    {NOTE_G4, TONE_QUARTER_NOTE},
    // 22
    {NOTE_F4, TONE_QUARTER_NOTE - TONE_BREAK_NOTE},
    {NOTE_MAXIMUM, TONE_BREAK_NOTE},
    {NOTE_F4, TONE_QUARTER_NOTE},
    // 23
    {NOTE_E4, TONE_QUARTER_NOTE - TONE_BREAK_NOTE},
    {NOTE_MAXIMUM, TONE_BREAK_NOTE},
    {NOTE_E4, TONE_QUARTER_NOTE},
    // 24
    {NOTE_D4, TONE_HALF_NOTE},
};

static tone_t tones_sub[] = {
    // Add notes here
};